### ISSUE TITLE
position encoding

### ISSUE THREAD

**Issue by Flaick** [lalithjets/Surgical_VQA#2]
Hello, I am wondering if you guys use any 2D positional encoding to add to the visual feature tokens? If not, is there any reason why? Thanks!

**Comment by lalithjets** [comment]
Hi Flaick,

We didn't explicitly use pos embedding for visual tokens. We used the default embedding from the VisualBert model.  We are currently exploring the effects of pos embedding. 

For default embedding, you can look through the  ([official huggingface VisualBert code](https://github.com/huggingface/transformers/blob/v4.26.1/src/transformers/models/visual_bert/modeling_visual_bert.py#L677), line 65-194. 

Have a good day.
