### ISSUE TITLE
Arguments of training and evaluation 

### ISSUE THREAD

**Issue by yuyangdu01** [lalithjets/Surgical_VQA#3]
Hi, thank you for your amazing work. Could you please provide the specific arguments of training and evaluation in EndoVis-18-VQA dataset? (The arguments are used in train_classification.py, etc) Thanks a lot!

**Comment by lalithjets** [comment]
Hi, I have just added the requested details to the readme file. hope it helps. As for evaluation for classification-based models, you can just extract the evaluation code from the 'train_classifiction.py' file and run them.
