### ISSUE TITLE
数据集链接失效

### ISSUE THREAD

**Issue by hylq66** [lalithjets/Surgical_VQA#4]
Hello, there is something wrong with downloading the link of EndoVis-18-VQA data set, the link of Cholec80 data set is invalid, could you please re-send the link of data set? You can also send Baidu web disk, Google cloud disk or mailbox, my mailbox is yujing_2018@126.com.

**(1) EndoVis18:** The official challenge website seems to have some errors. The following links were used to download the dataset. Do remember to cite the challenge paper (https://arxiv.org/pdf/2001.11190.pdf) if you use the images:
  - Train set 1, 1st half: https://mega.nz/#!tiY2xSZI!Tc6yqUI50Xh9A0LiSdFdNm0guu5rFCDtqKT05firvyU
  - Train set 1, 7 corrected frames: https://mega.nz/#!46YwBCZS!EolKDSipkmGOskDrSk51N8a7yeaGdAJF3zdY05nUbDs
  - Train set 1, 2nd half: https://mega.nz/#!Q2IACYKY!LUGQHxLGKUZuXlc6nnwOCD8eBxoapyINkaBhVy1Rb80
  - Train set 2, 1st half: https://mega.nz/#!s6ZwiAgS!bbrehM3IwTHrFnrkMI2MxW5blrpzspfbj6GGwBETe8k
  - Train set 2, 2nd half: https://mega.nz/#!5uRy1AZA!E6IdQQrfnp5LfjQB6nTD1mq1T2u5myk2StUEZem1M90
  - Test set: https://drive.google.com/drive/folders/1dySa4sIVUysAApKHqDzcyGxin8tAhfUi?usp=sharing

**(2) Cholec80:** You can request and download from: http://camma.u-strasbg.fr/datasets

_Originally posted by @lalithjets in https://github.com/lalithjets/Surgical_VQA/issues/1#issuecomment-1274935708_

**Comment by lalithjets** [comment]
Hi @hylq66,

Please approach the original authors (https://arxiv.org/pdf/2001.11190.pdf) of the challenge for the image dataset. The specific dataset generated for this project (the Q & A pairs) is still accessible through the link provided in the readme.
